# Generated by Django 5.1.2 on 2024-11-16 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('regular', 'Regular'), ('vet', 'Vet'), ('storeOwner', 'StoreOwner'), ('seller', 'Seller'), ('adopter', 'Adopter')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 'regular'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='user.user')),
                ('vet', models.ForeignKey(limit_choices_to={'user_type': 'vet'}, on_delete=django.db.models.deletion.CASCADE, related_name='vet_appointments', to='user.user')),
            ],
        ),
    ]
