# Generated by Django 5.1.2 on 2024-11-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostFound',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.TextField()),
                ('details', models.TextField()),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found'), ('reunited', 'Reunited')], max_length=20)),
            ],
        ),
    ]
