# Generated by Django 5.1.2 on 2024-11-16 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('store_type', models.CharField(choices=[('product', 'Product'), ('service', 'Service')], max_length=20)),
                ('store_owner', models.ForeignKey(limit_choices_to={'user_type': 'storeOwner'}, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_status', models.BooleanField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='GroomingService',
            fields=[
                ('service_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
                ('pet_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
    ]
