# Generated by Django 5.1.2 on 2024-11-16 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('health_status', models.TextField()),
                ('availability_status', models.BooleanField()),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 'regular'}, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
